#!/usr/bin/env python3
"""Compare two WizTree folder-export CSVs and show what grew/shrank/appeared/vanished."""
import csv
import sys


def load(path):
    with open(path, encoding="utf-8-sig") as f:
        next(f)  # skip "Generated by WizTree ..." banner line
        reader = csv.DictReader(f)
        return {row["File Name"]: int(row["Size"]) for row in reader}


def human_size(n):
    sign = "-" if n < 0 else "+" if n > 0 else ""
    n = abs(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024:
            return f"{sign}{n:.1f}{unit}"
        n /= 1024
    return f"{sign}{n:.1f}PB"


def compare(old_path, new_path, top_n=50):
    old, new = load(old_path), load(new_path)
    changes = []
    for path in old.keys() | new.keys():
        delta = new.get(path, 0) - old.get(path, 0)
        if delta != 0:
            changes.append((delta, path, path in old, path in new))

    changes.sort(reverse=True)
    lines = []
    for delta, path, was, is_ in changes[:top_n]:
        tag = "NEW" if not was else "GONE" if not is_ else "    "
        lines.append(f"{human_size(delta):>10} {tag} {path}")
    return lines


def summarize(old_path, new_path, top_n=25):
    old, new = load(old_path), load(new_path)
    grown, shrunk, appeared, vanished = [], [], [], []
    for path in old.keys() | new.keys():
        delta = new.get(path, 0) - old.get(path, 0)
        if delta == 0:
            continue
        if path not in old:
            appeared.append((delta, path))
        elif path not in new:
            vanished.append((delta, path))
        elif delta > 0:
            grown.append((delta, path))
        else:
            shrunk.append((delta, path))

    root_key = next((p for p in old.keys() & new.keys() if p.rstrip("\\").endswith(":")), None)
    net_delta = (new[root_key] - old[root_key]) if root_key else sum(d for d, _ in grown + shrunk + appeared + vanished)

    lines = [
        "=== Summary ===",
        f"Net change: {human_size(net_delta)}",
        f"Folders grown: {len(grown)}, shrunk: {len(shrunk)}, new: {len(appeared)}, removed: {len(vanished)}",
        "",
        f"Top {top_n} growth:",
    ]
    for delta, path in sorted(grown + appeared, reverse=True)[:top_n]:
        tag = "NEW " if (delta, path) in appeared else "     "
        lines.append(f"  {human_size(delta):>10} {tag}{path}")

    if shrunk or vanished:
        lines.append("")
        lines.append(f"Top {top_n} shrinkage / removals:")
        for delta, path in sorted(shrunk + vanished)[:top_n]:
            tag = "GONE " if (delta, path) in vanished else "     "
            lines.append(f"  {human_size(delta):>10} {tag}{path}")

    return lines


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <old.csv> <new.csv>")
        sys.exit(1)

    for line in summarize(sys.argv[1], sys.argv[2]):
        print(line)
    print()
    print("=== Full diff (top 50) ===")
    for line in compare(sys.argv[1], sys.argv[2]):
        print(line)


if __name__ == "__main__":
    main()
